Spam protection: Added ability to enable/disable email notifications
mfts/papermark pull request #134
Opened 2023-10-31 11:41 UTC by vndpal

Spam Protection: Ability to pause/resume email notifications #128

This PR offers our users the ability to pause or resume email notifications for document views.
Users can enable or disable this option by editing a link.

![image](https://github.com/mfts/papermark/assets/39481600/ff241fdd-26e9-4f4c-af60-4f49369f2fc9)

By default, this setting will be enabled, which means that document view emails will be sent to them. If they want to stop these emails, they can modify the link and turn off the option. Also, when creating a new link, they have the choice to set the notification option to "disabled."

I have added a text message at the bottom of the email which let our users know about the option to disable the email notification for the link

![image](https://github.com/mfts/papermark/assets/39481600/c4f75b92-5583-46dd-98e2-4f71b2d98142)

Let me know if this text needs to be changed or removed completely.

2023-11-11 12:44 UTC, mfts requested changes
@vndpal great job! minor text change. 

Otherwise, please update from `main` and resolve the 3 conflicts (nothing difficult). 
Happy to merge it afterwards :)

2023-11-11 12:44 UTC, mfts commented on components/emails/viewed-document.tsx
> +                To stop email notifications for this link views, edit the link
```suggestion
                To stop email notifications for this link, edit the link
```

2023-11-13 13:28 UTC, vndpal commented on components/emails/viewed-document.tsx
> +                To stop email notifications for this link views, edit the link
text changes done as suggested

2023-11-13 13:38 UTC, vndpal commented
@mfts resolved conflicts and made minor text changes as requested.

2023-11-13 13:49 UTC, mfts approved these changes
LGTM 🚀

2023-11-13 13:53 UTC, merged