feat: notification
mfts/papermark pull request #148
Opened 2023-11-11 08:12 UTC by Aashish-Upadhyay-101

2023-11-21 04:06 UTC, mfts requested changes
Looks really good @Aashish-Upadhyay-101 ! 
I think this feature will enable a lot of great use cases. 
I made in-line notes. 

Another thing that I noticed, you currently scoped `Notification` and `Webhook` by `User`. I think we need to scope it by `Team` instead. 
I don't think you need to change the API routes, you just need to request the current teamId from the user inside the API functions. 


Let me know if you have any questions about it

2023-11-21 04:06 UTC, mfts commented on lib/types.ts
> +  event: Event;
I think `Event` needs to be typed or at least imported from prisma-client

2023-11-21 04:06 UTC, mfts commented on pages/api/notifications/webhooks.ts
> +    // TODO: signature verification
What's your plan with the signature verification? 

Check out this implementation, perhaps it's helpful: https://github.com/leerob/on-demand-isr/blob/main/app/api/webhook/route.ts

2023-11-21 04:06 UTC, mfts commented on pages/api/notifications/webhooks.ts
> +      }
should we be checking this here or in the `handleLinkViewed` function?

2023-11-21 04:06 UTC, mfts commented on pages/api/notifications/webhooks.ts
> +      return res.status(201).json("hello");
Probably want to return something more useful to the webhook request

2023-11-21 04:06 UTC, mfts commented on pages/api/notifications/webhooks.ts
> +      console.log(error as Error);
same here. we want to return an error to the webhook

2023-11-21 04:06 UTC, mfts commented on lib/webhooks.ts
> +  eventData: any;
ideally we have a proper type for `eventData` but we can add this in afterwards

2023-11-21 04:06 UTC, mfts commented on lib/webhooks.ts
> +    }
can we simplify the prisma request with something like 

```
const webhooks = prisma.webhook.findMany({
   where: {
       userId,
       events: { in: [evenType] }
   }, 
   select: { targetUrl: true }
   })
```

then we are saving a conditional and we know we have the correct webhooks already. 

---
I haven't validated the prisma request

2023-11-21 04:06 UTC, mfts commented on lib/webhooks.ts
> +  });
we should return something from this promise. so that we can properly return errors

2023-11-21 04:06 UTC, mfts commented on pages/api/views.ts
> +      },
Why do we need the view count on the link request?

2023-11-21 04:06 UTC, mfts commented on tailwind.config.js
> +          "-ms-overflow-style": "mone",
is this a typo `"mone"`?

2023-11-21 04:06 UTC, mfts commented on prisma/schema.prisma
> +  LINKED_SHARED // When a user shares a document link with others.
```suggestion
  LINK_VIEWED // When a shared document link is viewed by someone.
  LINK_SHARED // When a user shares a document link with others.
```

should be updated everywhere it's used

2023-11-21 04:06 UTC, mfts commented on prisma/schema.prisma
> +  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)
I think the `webhook` should be connected on the team level instead of `user`

2023-11-21 04:06 UTC, mfts commented on lib/notifications/notification-handlers.ts
> +        documentId: eventData.data.documentId,
The `linkId` is missing. I think it's important to record which exact link was viewed on a document.

2023-11-21 04:06 UTC, mfts commented on prisma/schema.prisma
> +  webhooks                   Webhook[]
should be connected on the `team` level, not user level

2023-11-21 04:06 UTC, mfts commented on prisma/schema.prisma
> +  user       User     @relation(fields: [userId], references: [id], onDelete: Cascade)
Notifications should be also scoped by `team` so that i'm receiving the proper notifications for the team i'm part of

2023-11-22 12:06 UTC, Aashish-Upadhyay-101 commented on lib/types.ts
> +  event: Event;
done 👍

2023-11-22 12:11 UTC, Aashish-Upadhyay-101 commented on pages/api/notifications/webhooks.ts
> +      }
yes, I have moved it inside `handleLinkViewed` function, thanks for pointing this out :)

2023-11-22 12:52 UTC, Aashish-Upadhyay-101 commented on pages/api/views.ts
> +      },
I think I was testing something : ) I will fix this

2023-11-22 12:53 UTC, Aashish-Upadhyay-101 commented on tailwind.config.js
> +          "-ms-overflow-style": "mone",
oh yes, that is a typo should be `none`

2023-11-22 15:19 UTC, Aashish-Upadhyay-101 commented on pages/api/notifications/webhooks.ts
> +    // TODO: signature verification
done 👍

2023-12-08 05:11 UTC, Aashish-Upadhyay-101 commented
@mfts webhook and notification now have 3 events i.e. `document.uploaded`, `document.deleted` and `document.viewed`.
waiting for your review ; )

2025-04-26 16:03 UTC, closed without merging