feat: Clickable docs links
mfts/papermark pull request #274
Opened 2024-02-05 16:55 UTC by Aashish-Upadhyay-101

fixes #253 

@mfts the method used to implement this is very simple, will find a good work around this later ; ) 

for now, I think it's good. 

Ready for Review

2024-02-06 04:15 UTC, mfts commented
@Aashish-Upadhyay-101 wow nice work! I cannot wait to review this one 🎉

2024-02-12 09:34 UTC, mfts requested changes

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +            )}
```suggestion
          <div className="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0 space-x-4">
            {embeddedLinks && embeddedLinks.length > 0 ? (
              <DropdownMenu>
                <DropdownMenuTrigger>
                  <div className="text-sm font-semibold mr-6">
                    Embedded Links
                  </div>
                </DropdownMenuTrigger>
                <DropdownMenuContent className="space-y-2 pt-2 px-4">
                  {embeddedLinks.map((link, index) => (
                    <Link
                      href={link}
                      target="_blank"
                      className="text-sm flex items-start gap-2"
                      key={index}
                    >
                      <span>{index + 1}.</span>
                      <span className="underline">{link}</span>
                    </Link>
                  ))}
                </DropdownMenuContent>
              </DropdownMenu>
            ) : null}
```

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +                    Embedded Links
```suggestion
                    Links on Page
```

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +                    </Link>
You can just use a `<DropdownMenuItem>` from shadcn/ui and the links will be styled properly. 

Please remove the numbering `<span>{index + 1}.</span>`, I don't think that's needed

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +                  </div>
You can wrap this in a `<Button>` and then it will be styled well.

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +                    <Link
Add `rel="noopener noreferrer"` to the `<Link>` object

2024-02-12 09:34 UTC, mfts commented on components/view/nav.tsx
> +import DropDown from "../web/alternatives/dropdownproto";
this is probably not needed here

2024-02-13 16:53 UTC, Aashish-Upadhyay-101 commented
@mfts suggested fixes done !

2024-02-17 08:42 UTC, mfts approved these changes
Well done! Great work 👏

![giphy-2](https://github.com/mfts/papermark/assets/4049052/bb0350b3-70e5-4814-9b87-029360cebaff)

2024-02-17 09:02 UTC, merged