enhance: polished documents dashboard page
mfts/papermark pull request #275
Opened 2024-02-06 09:29 UTC by ashrafchowdury

## Description

Polished the document dashboard page, made it responsive for all devices, and added a proper skeleton loader for all components.

## Changes

1. Added Icons on Dropdown items and Stats cards.
2. Realigned components.
3. Added blazingly-looking skeleton loader.
4. Made it responsive for all devices.
5. Fixed the #193 issue.
6. Removed unnecessary elements
7. Added all dashboard skeleton loaders into a skeleton folder for better organization.
8. Realigned the file upload progress bar.
9. Improved the component's conditional rendering.
10. ...

## Preview

https://github.com/mfts/papermark/assets/87828904/4fb22e43-3d89-4da7-b1c2-9be52cecc733

**New location of the file upload progress bar.**

![image](https://github.com/mfts/papermark/assets/87828904/8fb4570f-49d0-4e94-9847-6e9bec92c7da)

## Issue

Closes #193

2024-02-12 08:23 UTC, mfts commented
Thanks for the PR @ashrafchowdury -- taking a look now

2024-02-12 09:00 UTC, mfts requested changes

2024-02-12 09:00 UTC, mfts commented on components/links/link-sheet/domain-section.tsx
The idea of this selector was to show that the input field is the /slug to the domain. 

The new implementation removes that implication completely. Ideally revert to the old state

2024-02-12 09:00 UTC, mfts commented on components/documents/stats-element.tsx
> +        </div>
Not a huge fan of icons here. They don't really add value. The dashboard should not be distracting but minimalistic. 

Please remove the need for icons in the stats element

2024-02-12 09:00 UTC, mfts commented on components/links/links-table.tsx
> +                                  <FilePen className="w-4 h-4 mr-2" /> Edit Link
Same here with the icon. it's not adding value

2024-02-12 09:00 UTC, mfts commented on components/skeletons/links-table-sekeleton.tsx
Since these Skeletons are so tailored to each of the components, it would make more sense to co-locate the skeletons with each component. That way it will be easy to adjust and find them when working on a component

2024-02-12 10:33 UTC, ashrafchowdury commented on components/skeletons/links-table-sekeleton.tsx
Re-located all the skeletons into their main components.

2024-02-12 10:33 UTC, ashrafchowdury commented on components/documents/stats-element.tsx
> +        </div>
removed

2024-02-12 10:34 UTC, ashrafchowdury commented on components/links/link-sheet/domain-section.tsx
Reverted domain slug component into its old state

2024-02-13 09:22 UTC, mfts approved these changes
Great work. looks really nice

2024-02-13 09:53 UTC, merged