feat: Link specific page in document
mfts/papermark pull request #308
Opened 2024-02-25 06:34 UTC by ashrafchowdury

## Description

Implemented a new feature that allows users to create hyperlinks (`?p=5`) within a document that jumps to specific pages. This functionality will improve navigation and information accessibility within long documents.

## Changes
1. Created a new function named `updatePageNumberInUrl` to update the page number on the URL
3. Used useEffect hook to jump users to specific pages if the `?p=` search parameter is available

## Preview

https://github.com/mfts/papermark/assets/87828904/e7c642d2-6458-47cf-9d8d-5fe63322c232

## Issue

Closes #306

2024-02-27 03:01 UTC, mfts commented on components/view/PagesViewer.tsx
> +import { useSearchParams, useRouter, usePathname } from "next/navigation";
Since `<PagesViewer>` component is rendered in the pages router, not the app router of next.js, we need to use `useRouter from next/router` instead of next/navigation. 

Then we can use `const router = useRouter()` and access the url query params with `const { p } = router.query`

2024-02-27 03:06 UTC, mfts commented on components/view/PagesViewer.tsx
> +
I don't think we need a router push here. The page will render based on the state of the `setPageNumber` automatically the correct page. 

So all we need to check for is the existing query param `p` and then setPageNumber to that value if it's less than the `numPages`.

2024-02-27 03:07 UTC, mfts commented on components/view/PagesViewer.tsx
> +
If we can do it without a `useEffect` would be my preferred option :)

2024-02-27 14:38 UTC, ashrafchowdury commented on components/view/PagesViewer.tsx
> +
I used the router push here to keep track of the page number on the query. So, if a user reloads the page, they can continue reading from where they left off. 

Is that make sense?

2024-02-27 16:55 UTC, ashrafchowdury commented
Improved the overall workflow of this feature by removing the `useEffect` hook and hard-pushing the `query` value.

I'm using the `updatePageNumberInUrl` function to track the user's current page number and then if they share the URL with someone they can easily access that specific page.

**The tracking of user page numbers has been updated to improve efficiency. The query will now be updated silently without rerendering the application.**

### Preview
https://github.com/mfts/papermark/assets/87828904/caaf0e6e-4e7e-4fc8-a9f7-a39d45d8aa14

2024-02-28 09:30 UTC, mfts requested changes

2024-02-28 09:30 UTC, mfts commented on components/view/PagesViewer.tsx
> +
I don't think we need to update the url / query when the user changes pages

2024-02-28 09:30 UTC, mfts commented on components/view/PagesViewer.tsx
> +    updatePageNumberInUrl(pageNumber - 1);
as per comment below this can be removed

2024-02-28 09:30 UTC, mfts commented on components/view/PagesViewer.tsx
> +    updatePageNumberInUrl(pageNumber + 1);
as per comment below this can be removed

2024-02-28 09:30 UTC, mfts commented on components/view/PagesViewer.tsx
> +    pageQuery <= numPages ? pageQuery : 1,
```suggestion
    pageQuery >= 1 && pageQuery <= numPages ? pageQuery : 1,
```

just to make sure that the user doesn't enter a negative number

2024-02-28 14:51 UTC, ashrafchowdury commented on components/view/PagesViewer.tsx
> +    pageQuery <= numPages ? pageQuery : 1,
updated the logic 🙌

2024-02-29 04:42 UTC, mfts approved these changes
Thanks! Really elegant solution in the end 🎉

2024-02-29 05:24 UTC, merged