Show empty state when there are no documents available
mfts/papermark pull request #5
Opened 2023-06-01 06:03 UTC by dephraiim

## Screenshots
![Papermark Ephraim Atta-Duncan PR Screenshot](https://github.com/mfts/papermark/assets/55143799/3bc478db-c370-4919-9a14-bcf809e67d6a)
![localhost_3000_documents (4)](https://github.com/mfts/papermark/assets/55143799/ff6f9e54-07e5-4a28-b1ef-c5fc682c8caa)

2023-06-01 10:27 UTC, mfts requested changes

2023-06-01 10:27 UTC, mfts commented on components/Sidebar.tsx
By removing the "New Link" button from the Sidebar component, it won't be available anywhere. Make sure it's only removed on the /documents page, but still visible on other pages.

2023-06-05 11:02 UTC, mfts requested changes

2023-06-05 11:02 UTC, mfts commented on components/Sidebar.tsx
> +            {!isDocumentsRoute ? (
You need to add a check in to show the "new link" button if there are documents available. 

Right now it only checks for the route and assumes `documents.length == 0`

2023-06-13 21:07 UTC, merged

2023-06-13 21:09 UTC, mfts commented
Thanks @dephraiim. I added some small changes

2023-06-13 21:10 UTC, dephraiim commented
Looks like I missed the changes request, sorry about that.