Document delete
mfts/papermark pull request #81
Opened 2023-09-23 15:30 UTC by Aashish-Upadhyay-101

Fix #75

2023-09-24 17:24 UTC, mfts commented
Thanks for the PR @Aashish-Upadhyay-101  will review and merge this one tomorrow :)

2023-09-27 18:31 UTC, mfts requested changes

2023-09-27 18:31 UTC, mfts commented on pages/api/documents/[id]/index.ts
> +      })
I would suggest wrapping both of these in a Promise.all

2023-09-27 18:31 UTC, mfts commented on pages/api/documents/[id]/index.ts
> +    // We only allow GET, DELETE and POST requests
```suggestion
    // We only allow GET and DELETE requests
```

I realized that there's no POST request in this API route

2023-09-28 18:39 UTC, Aashish-Upadhyay-101 commented
@mfts new changes : )

2023-09-30 06:59 UTC, mfts approved these changes
great work @Aashish-Upadhyay-101 !

2023-10-01 12:02 UTC, merged