feat: delete link
mfts/papermark pull request #82
Opened 2023-09-25 06:59 UTC by Aashish-Upadhyay-101

fix #75

2023-09-27 18:47 UTC, mfts requested changes

2023-09-27 18:47 UTC, mfts commented on pages/api/links/[id]/index.ts
> +  } else if (req.method == "DELETE") {
```suggestion
  } else if (req.method == "DELETE") {
  // DELETE /api/links/:id
```

2023-09-27 18:47 UTC, mfts commented on pages/api/links/[id]/index.ts
> +      });
I think we should add a way to determine that the user requesting to delete the link is actually authorized to delete the link. 

I like that you put this method in here. 
This allows us to compare the ownerId with the session userId, if you include the `document: { ownerId: true }`  on this function.

2023-09-28 19:00 UTC, Aashish-Upadhyay-101 commented
@mfts changes done !

2023-09-30 06:53 UTC, mfts approved these changes
nice work @Aashish-Upadhyay-101 !

2023-09-30 07:00 UTC, merged