[FEATURE] Added feature Export Visits to download the csv of Visits and Views
mfts/papermark pull request #840
Opened 2024-10-12 16:20 UTC by aryany9

This PR adds the Export Visits functionality to download the Visits counts in an csv file on "Export Visits" button click.

Quick Video showing the solution.

https://github.com/user-attachments/assets/eee3d12f-0164-4fad-8583-0214de0be8ea

2024-10-12 16:21 UTC, aryany9 commented
I have read the CLA Document and I hereby sign the CLA

2024-10-12 16:21 UTC, aryany9 commented
recheck

2024-10-13 06:20 UTC, aryany9 commented
@mfts  Please attach the oss.gg labels as well. They were not assigned by the bot.

2024-10-14 03:25 UTC, mfts requested changes
@aryany9 the package you used is abandoned! please make sure you review packages before adding anything external. 

please change the approach to do it without an external library. 
for example, something like this: https://dev.to/graciesharma/implementing-csv-data-export-in-react-without-external-libraries-3030

2024-10-14 03:25 UTC, mfts commented on package.json
> +    "json2csv": "^6.0.0-alpha.2",
@aryany9 this package is abandoned. please remove it and change the approach
https://www.npmjs.com/package/json2csv

2024-10-15 10:28 UTC, aryany9 commented
Hi @mfts, Thankyou for pointing out the abandoned package. It has been removed and the approach has been changed as well. I have tested it with the new approach it is working as expected. Do let me know if you require any more changes. Thankyou.

2024-10-16 05:33 UTC, mfts approved these changes
Looks amazing! Thanks so much for following the request and making it native without an external parser :)

2024-10-16 05:46 UTC, merged