fixed: added responsiveness to button for better visualization
mfts/papermark pull request #845
Opened 2024-10-12 17:35 UTC by souvikjs01

fixes #843 
The "Upgrade to invite members" button at https://app.papermark.io/settings/people is almost invisible
expected behavior- button content should be properly aligned.
![Screenshot 2024-10-12 193640](https://github.com/user-attachments/assets/925b392f-1717-4afb-8430-9affe4efef4e)

current view:
![Screenshot 2024-10-12 220937](https://github.com/user-attachments/assets/5750c9ce-6fca-4795-9838-6f41e8b8de5a)

2024-10-14 15:35 UTC, mfts requested changes
Please remove the changes in the package-lock.json

2024-10-14 15:35 UTC, mfts commented on package-lock.json
@souvikjs01 could you remove this file change please.

2024-10-14 18:50 UTC, souvikjs01 commented on package-lock.json
Ohh sorry my bad, let me remove the changes in pack-lock.json file.

2024-10-19 09:18 UTC, mfts approved these changes

2024-10-19 09:31 UTC, merged