feat: preview link as
mfts/papermark pull request #849
Opened 2024-10-12 18:41 UTC by yashsharma999

Fixes #696

## Description
Quickly view the document/dataroom without going through access form, nda, verification etc.

## Screenshots
<img width="593" alt="Screenshot 2024-10-13 at 12 08 58 AM" src="https://github.com/user-attachments/assets/f249f903-24c8-4a30-bd39-916bd95cc2f6">

2024-10-14 15:38 UTC, mfts requested changes
I like it. But it's potentially exploitable because it's just a url query param. 

Instead we need to verify it server-side and only allow it if `previewToken` passes

2024-10-14 19:14 UTC, yashsharma999 commented
alright, but essentially we need to somehow bypass `isProtected` prop if i'm not wrong ? 

```
isProtected={
            viewAs === "QUICK_PREVIEW"
              ? false
              : !!(emailProtected || linkPassword || enableAgreement)
          }
```

2024-10-19 09:22 UTC, mfts commented
> but essentially we need to somehow bypass isProtected prop if i'm not wrong ?

@yashsharma999 yes that's correct. but right now with your current implementation, you could add `?viewAs=QUICK_VIEW` to any normal link and it would bypass the `isProtected`. 

Also as I'm writing it, we double check server-side actually if the link is protected again, so you'd need to pass something to the api function to get around the protection

2024-10-27 10:59 UTC, mfts commented
@yashsharma999 I'm closing this PR for now as I didn't hear back from you and it's not a big dealbreaker at the moment. 

I'm still reviewing your other PRs. 

I'm also rewarding you for your effort nonetheless! 
/award 150

2024-10-27 10:59 UTC, closed without merging