Integrated GitHub Authentication
mfts/papermark pull request #92
Opened 2023-10-07 06:32 UTC by lizardkingLK

This pull request contains 

- GitHub Authentication
- Minor UI Tweaks
- VSCode launch.json config

2023-10-07 09:16 UTC, mfts commented
Thabks for the submission. I'll have a look today :)

2023-10-08 10:13 UTC, lizardkingLK commented
> Thanks for the submission. I'll have a look today :)

Thanks

2023-10-17 07:15 UTC, lizardkingLK commented
@mfts hey is there a way this can get accepted?

2023-10-18 09:22 UTC, mfts requested changes
Beside the inline comments, there are two other things that have come to my attentions. 

1. GitHub stores an additional field in the database [`refresh_token_expires_in`, which needs to be added to `Account` model in schema.prisma](https://next-auth.js.org/providers/github#:~:text=GitHub%20returns%20a%20field%20on%20Account%20called%20refresh_token_expires_in%20which%20is%20a%20number.%20See%20their%20docs.%20Remember%20to%20add%20this%20field%20to%20your%20database%20schema%2C%20in%20case%20if%20you%20are%20using%20an%20Adapter.)

2. secondly if the user has previously signup with another account with the same email, then it throws an **OAuthAccountNotLinked** error, which should be handled with a message saying something like "account with this email already exists, please use a different login method"

2023-10-18 09:22 UTC, mfts commented on components/ui/loader.tsx
This component is no longer required. we have `@/components/ui/loading-spinner`

2023-10-18 09:22 UTC, mfts commented on pages/login.tsx
> +            </svg>
Please use the existing GitHub icon component: `@/components/shared/icons/github.tsx`

2023-10-18 09:22 UTC, mfts commented on .vscode/launch.json
please exclude this file from the PR. it's your local preference but some other users may use a different editor or setup. :)

2023-10-18 09:22 UTC, mfts commented on pages/documents/[id].tsx
something with the formatting went wrong here. please revert changes on this file. it's not required to be edited for this PR. the exact error is that one of the div closes too early and there's an unclosed fragment. by reverting your changes it should fix this issue on this page

2023-10-23 04:07 UTC, lizardkingLK commented
Thanks a lot. I will check.

2023-11-23 05:47 UTC, closed without merging